function randomizeFromArray(array) {
  return array[Math.floor(Math.random() * array.length)];
}


export const maleSlavicNames = {
  type: "picker",
  list: [
    "Bachorza",
    "Baran",
    "Barcław",
    "Barcsław",
    "Barnim",
    "Barnisław",
    "Bądzsław",
    "Bąsław",
    "Bdzigost",
    "Bedgost",
    "Bezprym",
    "Będomir",
    "Będzieciech",
    "Będziemir",
    "Będziemirz",
    "Będzimir",
    "Będzimysł",
    "Biecław",
    "Biecsław",
    "Biestryj",
    "Biezdar",
    "Biezdziad",
    "Biezpraw",
    "Biezprzem",
    "Biezprzym",
    "Biezrząd",
    "Biezstryj",
    "Biezstryk",
    "Biezuj",
    "Biezwuj",
    "Blizan",
    "Blizbor",
    "Blizborz",
    "Bochwał",
    "Bodan",
    "Bodzepor",
    "Bofał",
    "Bogchwał",
    "Bogdaj",
    "Bogdał",
    "Bogdan",
    "Bogdasz",
    "Bogfał",
    "Bogmieł",
    "Bogmił",
    "Bogodał",
    "Bogodan",
    "Bogodar",
    "Bogofał",
    "Bogomieł",
    "Bogomił",
    "Bogosław",
    "Bogowid",
    "Bogsław",
    "Boguchał",
    "Boguchwał",
    "Bogudan",
    "Bogudar",
    "Bogufał",
    "Bogumieł",
    "Bogumił",
    "Bogumysław",
    "Bogurad",
    "Bogured",
    "Bogusąd",
    "Bogusław",
    "Bogwidza",
    "Bogwiedz",
    "Bohusław",
    "Bojan",
    "Bolan",
    "Bolebor",
    "Boleczaj",
    "Boleczest",
    "Bolegor",
    "Bolelut",
    "Bolemir",
    "Bolemysł",
    "Bolesław",
    "Bolesta",
    "Bolęta",
    "Bolibąd",
    "Bolibor",
    "Bolko",
    "Boromir",
    "Borut",
    "Boruta",
    "Borzej",
    "Borzęta",
    "Borzgniew",
    "Borzuj",
    "Borzygniew",
    "Borzym",
    "Borzymir",
    "Borzysław",
    "Borzywoj",
    "Borzywuj",
    "Bosław",
    "Bożciech",
    "Bożdar",
    "Bożebor",
    "Bożeciech",
    "Bożydar",
    "Bożysław",
    "Bracsław",
    "Branibor",
    "Bratek",
    "Bratmił",
    "Bratomił",
    "Bratomir",
    "Bratosław",
    "Bratosz",
    "Bratumił",
    "Braturad",
    "Bratysław",
    "Bretmił",
    "Bretomił",
    "Brocsław",
    "Broda",
    "Brodzisław",
    "Bromir",
    "Bronimir",
    "Bronisąd",
    "Bronisław",
    "Broniwoj",
    "Bronsław",
    "Brosław",
    "Brunisław",
    "Brzestryk",
    "Brzezdob",
    "Brzezdoma",
    "Brzezpraw",
    "Brzezstryk",
    "Budziboj",
    "Budzigniew",
    "Budzimir",
    "Budzisław",
    "Budziwoj",
    "Budziwuj",
    "Budzsław",
    "Budźwoj",
    "Byczek",
    "Bygost",
    "Bytomir",
    "Chalimir",
    "Chalisław",
    "Chełst",
    "Chocian",
    "Chociebąd",
    "Chociebor",
    "Chociemir",
    "Chociesław",
    "Chocimier",
    "Chocimir",
    "Chocimirz",
    "Chocsław",
    "Choroman",
    "Chotobor",
    "Chrap",
    "Chudz",
    "Chwalęta",
    "Chwalibog",
    "Chwalimir",
    "Chwalisław",
    "Cibor",
    "Cich",
    "Ciechomir",
    "Ciechosław",
    "Ciecierad",
    "Cieciered",
    "Ciecimiar",
    "Ciecirad",
    "Cieciurad",
    "Ciećrad",
    "Cierpisław",
    "Ciesław",
    "Cieszbor",
    "Cieszęta",
    "Cieszmiar",
    "Cieszmier",
    "Cieszmir",
    "Cieszybor",
    "Cieszygor",
    "Cieszym",
    "Cieszymiar",
    "Cieszymier",
    "Cieszymir",
    "Cieszymysł",
    "Cieszyrad",
    "Cieszysław",
    "Cirzpibog",
    "Cirzpisz",
    "Cis",
    "Cisław",
    "Czabor",
    "Czajęta",
    "Czasław",
    "Czcibor",
    "Czcirad",
    "Czcisław",
    "Czedrog",
    "Czesbor",
    "Czesław",
    "Czębor",
    "Czędomir",
    "Częsbor",
    "Częstobor",
    "Częstogoj",
    "Częstomir",
    "Częstowoj",
    "Czścibor",
    "Dadzbog",
    "Dalbor",
    "Dalebor",
    "Daleborz",
    "Dalegor",
    "Dalemiar",
    "Dalemir",
    "Dalestryj",
    "Dalewin",
    "Dalibor",
    "Dalimiar",
    "Dalimir",
    "Dalwin",
    "Dargomier",
    "Dargorad",
    "Dargosław",
    "Derwan",
    "Długomił",
    "Dobiegniew",
    "Dobielut",
    "Dobiemiar",
    "Dobiemier",
    "Dobiemiest",
    "Dobiemir",
    "Dobiesław",
    "Dobimir",
    "Dobosław",
    "Dobrobąd",
    "Dobrociech",
    "Dobrogniew",
    "Dobrogost",
    "Dobrogoszcz",
    "Dobromier",
    "Dobromił",
    "Dobromir",
    "Dobromysł",
    "Dobromysław",
    "Dobrosiodł",
    "Dobrosław",
    "Dobrosuł",
    "Dobrowit",
    "Dobrowoj",
    "Dobrutro",
    "Dobrzegniew",
    "Domabor",
    "Domaborz",
    "Domagniew",
    "Domamir",
    "Domarad",
    "Domaradz",
    "Domared",
    "Domasław",
    "Domastoj",
    "Domastryj",
    "Domasuł",
    "Domauj",
    "Domawuj",
    "Domażyr",
    "Domiemir",
    "Domk",
    "Domorad",
    "Domosław",
    "Drahobysz",
    "Drahomir",
    "Drogmir",
    "Drogodziej",
    "Drogomił",
    "Drogomir",
    "Drogomysł",
    "Drogoradz",
    "Drogosław",
    "Drogowit",
    "Drohobysz",
    "Drohomir",
    "Dromił",
    "Dziebor",
    "Dziersław",
    "Dzierżykraj",
    "Dzierżysław",
    "Dziesław",
    "Dzik",
    "Dzirsław",
    "Dzirżykraj",
    "Dzirżysław",
    "Dzirżyterg",
    "Dzirżywuj",
    "Dzisław",
    "Dziwigor",
    "Dziwisław",
    "Falibog",
    "Falibor",
    "Falimir",
    "Falimirz",
    "Falisław",
    "Gardomir",
    "Gęba",
    "Głowka",
    "Gniemir",
    "Gnierat",
    "Gniewko",
    "Gniewomiar",
    "Gniewomier",
    "Gniewomir",
    "Gniewosz",
    "Gocław",
    "Godosław",
    "Godzimir",
    "Godzisław",
    "Godzsław",
    "Gogoła",
    "Gołek",
    "Goły",
    "Gorazd",
    "Gorsław",
    "Gorzysław",
    "Gosław",
    "Gostmił",
    "Gostomysł",
    "Gościmiar",
    "Gościmir",
    "Gościrad",
    "Gościsław",
    "Gościwid",
    "Gościwit",
    "Gościwuj",
    "Goworek",
    "Grochot",
    "Grodzisław",
    "Grodzsław",
    "Gromisław",
    "Grot",
    "Grzmisław",
    "Grzymisław",
    "Grzymosław",
    "Grzymsław",
    "Grzysław",
    "Himisław",
    "Hodysław",
    "Hubysław",
    "Huniemir",
    "Huniesław",
    "Imisław",
    "Izasław",
    "Izbelut",
    "Izbor",
    "Izbygniew",
    "Izbylut",
    "Jaczemir",
    "Jaczewoj",
    "Jaksa",
    "Janisław",
    "Jarogniew",
    "Jaromiar",
    "Jaromir",
    "Jaropełk",
    "Jarosław",
    "Jarostryj",
    "Jawor",
    "Jerogniew",
    "Jeromiar",
    "Jeromier",
    "Jerosław",
    "Jezior",
    "Jeż",
    "Jimisław",
    "Jirosław",
    "Juniesław",
    "Jutrogost",
    "Jutrowoj",
    "Jutrowuj",
    "Kajmir",
    "Kalmir",
    "Kanimier",
    "Kanimir",
    "Kanmił",
    "Karna",
    "Kazimiar",
    "Kazimier",
    "Kazimierz",
    "Kazimir",
    "Kazimirz",
    "Kaźmir",
    "Kąkol",
    "Kierz",
    "Kłobuczek",
    "Kobyłka",
    "Kochan",
    "Kociebor",
    "Kociemiar",
    "Kociemier",
    "Kociemir",
    "Kocimiar",
    "Kocimier",
    "Kocimir",
    "Koćmir",
    "Komor",
    "Koprzywa",
    "Korostawic",
    "Korostawiec",
    "Kościoł",
    "Kożuszek",
    "Krasa",
    "Krost",
    "Krupa",
    "Kruszk",
    "Krzecsław",
    "Krzesąd",
    "Krzesimir",
    "Krzesisław",
    "Krzesław",
    "Krzysław",
    "Krzywosąd",
    "Krzyż",
    "Kupimir",
    "Kusza",
    "Kwalimir",
    "Kwalisław",
    "Kwiatek",
    "Laliczaj",
    "Lasota",
    "Lech",
    "Lechosław",
    "Lederg",
    "Lelistryj",
    "Lesław",
    "Leszek",
    "Lis",
    "Litobor",
    "Luba",
    "Lubgost",
    "Lubodrog",
    "Lubomir",
    "Lubomirz",
    "Lubomysł",
    "Luboradz",
    "Lubowid",
    "Lucsław",
    "Ludmar",
    "Ludmił",
    "Ludomer",
    "Ludomił",
    "Ludomir",
    "Ludosław",
    "Ludziwoj",
    "Lutmiar",
    "Lutobor",
    "Lutogniew",
    "Lutomiar",
    "Lutomir",
    "Lutomysł",
    "Lutosław",
    "Lutsław",
    "Łękomir",
    "Łopata",
    "Małobąd",
    "Małogost",
    "Małomir",
    "Małostryj",
    "Małostryk",
    "Małowid",
    "Małowuj",
    "Manomir",
    "Markusław",
    "Masław",
    "Matuł",
    "Mezamir",
    "Męcimir",
    "Męcisław",
    "Męcsław",
    "Męsław",
    "Miecisław",
    "Miecsław",
    "Mieczysław",
    "Miełosław",
    "Miesław",
    "Miestwin",
    "Mieszek",
    "Mieszko",
    "Milan",
    "Milej",
    "Milęta",
    "Miłgost",
    "Miłobąd",
    "Miłobor",
    "Miłobrat",
    "Miłochat",
    "Miłoczat",
    "Miłodrog",
    "Miłodziad",
    "Miłogost",
    "Miłorad",
    "Miłosław",
    "Miłostryj",
    "Miłosz",
    "Miłowan",
    "Miłowit",
    "Miłowuj",
    "Miłwit",
    "Minigniew",
    "Minogniew",
    "Mirogniew",
    "Mirogod",
    "Mironieg",
    "Mirosław",
    "Mirzęta",
    "Misław",
    "Mleko",
    "Młoka",
    "Modlibog",
    "Modliboż",
    "Mogiłek",
    "Mojmir",
    "Mojsław",
    "Morzysław",
    "Mrocław",
    "Mrocsław",
    "Mroczesław",
    "Mroczsław",
    "Mroczysław",
    "Mrosław",
    "Mszczuj",
    "Mszczujwoj",
    "Mścibor",
    "Mścigniew",
    "Mścisław",
    "Mściwoj",
    "Mściwuj",
    "Mysław",
    "Myślibor",
    "Myślidar",
    "Myślim",
    "Myślimir",
    "Nacław",
    "Nacsław",
    "Naczęmiar",
    "Naczęmier",
    "Naczęmir",
    "Naczęrad",
    "Naczęsław",
    "Naczęwoj",
    "Naczęwuj",
    "Nadar",
    "Nadbor",
    "Nadmir",
    "Nadziej",
    "Nagod",
    "Namir",
    "Namysław",
    "Nasiębąd",
    "Nasiębor",
    "Nasiębud",
    "Nasięgniew",
    "Nasław",
    "Nawoj",
    "Nawuj",
    "Nażyr",
    "Niebor",
    "Niebylec",
    "Niecisław",
    "Niedabył",
    "Niedabysz",
    "Niedalic",
    "Niedał",
    "Niedamir",
    "Niedan",
    "Niedaniec",
    "Niedoma",
    "Niedomysł",
    "Niedrog",
    "Niegodoma",
    "Niegosław",
    "Niegowoj",
    "Niegrod",
    "Nielubiec",
    "Niemierz",
    "Niemir",
    "Niemironieg",
    "Niemoj",
    "Niemst",
    "Niemsta",
    "Niemszczon",
    "Nienach",
    "Niepełka",
    "Nieprasz",
    "Nieproch",
    "Nieprosz",
    "Nieprzebąd",
    "Nieprzebud",
    "Nieprzebysz",
    "Nierad",
    "Niered",
    "Nierod",
    "Niesiebąd",
    "Niesiebor",
    "Niesiebud",
    "Niesiodł",
    "Niestek",
    "Niestoj",
    "Niesuł",
    "Nietęg",
    "Nietubył",
    "Niewsza",
    "Niezamysł",
    "Nieznamir",
    "Nieznawuj",
    "Ninogniew",
    "Ninomysł",
    "Ninosz",
    "Ninota",
    "Ninowłod",
    "Nowosiodł",
    "Objęsław",
    "Ocięsław",
    "Odolan",
    "Okrzesław",
    "Opoka",
    "Osiębor",
    "Osięgniew",
    "Ostrobod",
    "Ostrogniew",
    "Ostrowod",
    "Pakosław",
    "Pełczybog",
    "Pęcisław",
    "Pęcław",
    "Pęcsław",
    "Pękosław",
    "Pępik",
    "Pęsław",
    "Pomian",
    "Pomir",
    "Pomścibor",
    "Poznan",
    "Poznomir",
    "Pożar",
    "Prosimir",
    "Przebąd",
    "Przebor",
    "Przecław",
    "Przecsław",
    "Przedabog",
    "Przedbor",
    "Przedmir",
    "Przedpełk",
    "Przedpołk",
    "Przedsław",
    "Przedwoj",
    "Przedwor",
    "Przedwuj",
    "Przemęt",
    "Przemieł",
    "Przemił",
    "Przemir",
    "Przemysł",
    "Przemysław",
    "Przemyślibor",
    "Przesław",
    "Przezdoma",
    "Przezdziad",
    "Przezmir",
    "Przezpraw",
    "Przezprzem",
    "Przyboj",
    "Przybor",
    "Przybygniew",
    "Przybylut",
    "Przybymir",
    "Przybyrad",
    "Przybysław",
    "Przybysza",
    "Przybywoj",
    "Przybywuj",
    "Przysnobor",
    "Przywit",
    "Psar",
    "Racibor",
    "Raciborz",
    "Racigniew",
    "Racimiar",
    "Racimir",
    "Racisław",
    "Racław",
    "Racsław",
    "Radmir",
    "Radociech",
    "Radogost",
    "Radomiar",
    "Radomił",
    "Radomir",
    "Radosław",
    "Radost",
    "Radosz",
    "Radowan",
    "Radowit",
    "Radowuj",
    "Radsław",
    "Radsuł",
    "Radzan",
    "Radzim",
    "Rasław",
    "Ratsław",
    "Recibor",
    "Recław",
    "Recsław",
    "Redosław",
    "Redsław",
    "Resław",
    "Retsław",
    "Rocław",
    "Rocsław",
    "Rodomieł",
    "Rodomił",
    "Rodsław",
    "Rolirad",
    "Rosław",
    "Rościgniew",
    "Rościsław",
    "Rozniat",
    "Rozniata",
    "Rus",
    "Rzędzimir",
    "Rzędzisław",
    "Rzędziwoj",
    "Sambor",
    "Samogost",
    "Samosąd",
    "Sęczygniew",
    "Sędomir",
    "Sędosław",
    "Sędowin",
    "Sędowoj",
    "Sędzigrod",
    "Sędzimir",
    "Sędzisław",
    "Sędziwoj",
    "Sędziwuj",
    "Sędźwoj",
    "Sężyr",
    "Siabor",
    "Sidło",
    "Siebąd",
    "Siebor",
    "Sieciebor",
    "Sieciech",
    "Sieciesław",
    "Siecław",
    "Siecsław",
    "Siedlewit",
    "Siemar",
    "Siemidrog",
    "Siemierz",
    "Siemił",
    "Siemimił",
    "Siemimysł",
    "Siemir",
    "Siemirad",
    "Siemisław",
    "Siemmił",
    "Siemomysł",
    "Siemomysław",
    "Siemoradz",
    "Siemosław",
    "Siemowit",
    "Siepraw",
    "Sierosław",
    "Siesław",
    "Siestrzemił",
    "Siestrzewit",
    "Sietbor",
    "Sięgniew",
    "Siężyr",
    "Sirosław",
    "Sjęgniew",
    "Skamir",
    "Skarbimir",
    "Skarbimirz",
    "Skarbisław",
    "Skardmir",
    "Skaziczest",
    "Sławciech",
    "Sławobor",
    "Sławociech",
    "Sławomiar",
    "Sławomir",
    "Sławosław",
    "Słup",
    "Smagor",
    "Smarz",
    "Smysław",
    "Snowid",
    "Sobiebor",
    "Sobiemir",
    "Sobiemysł",
    "Sobierad",
    "Sobiesąd",
    "Sobiesław",
    "Sobieżyr",
    "Solisław",
    "Spycigniew",
    "Spycimir",
    "Spycisław",
    "Spyćmier",
    "Spyćmierz",
    "Spyćmir",
    "Stanibor",
    "Stanimir",
    "Stanisław",
    "Stasław",
    "Stogniew",
    "Stoigniew",
    "Stoisław",
    "Stojan Wygnan",
    "Stojgniew",
    "Stojsław",
    "Stomir",
    "Stosław",
    "Strach",
    "Strachomir",
    "Strogobor",
    "Strogomir",
    "Stronisław",
    "Strosław",
    "Strzałek",
    "Strzebor",
    "Strzecław",
    "Strzecsław",
    "Strzedziwoj",
    "Strzedzsław",
    "Strzesław",
    "Strzesz",
    "Strzeszko",
    "Strzeżymir",
    "Strzeżysław",
    "Sudywoj",
    "Sulibor",
    "Sulibrat",
    "Sulidziad",
    "Suligost",
    "Sulim",
    "Sulima",
    "Sulimiar",
    "Sulimir",
    "Sulirad",
    "Sulisław",
    "Sulistryj",
    "Suliwuj",
    "Sulmir",
    "Swar",
    "Swojsław",
    "Swosław",
    "Szabor",
    "Szczęsny",
    "Szczodr",
    "Szebor",
    "Szenbor",
    "Szydło",
    "Ścibor",
    "Świebąd",
    "Świebor",
    "Świeborz",
    "Świeciech",
    "Świecław",
    "Świedarg",
    "Świegniew",
    "Świelub",
    "Świemił",
    "Świemir",
    "Świerad",
    "Świesław",
    "Święcesław",
    "Święcsław",
    "Święsław",
    "Świętobor",
    "Świętomir",
    "Świętopełk",
    "Świętosław",
    "Świrad",
    "Świrszcz",
    "Taniebor",
    "Tasław",
    "Tatomier",
    "Tatomir",
    "Tatumir",
    "Tęgomir",
    "Toligniew",
    "Tolisław",
    "Tomił",
    "Tomir",
    "Tomisław",
    "Tosław",
    "Trup",
    "Trzebiebor",
    "Trzebiegost",
    "Trzebiemiar",
    "Trzebiemier",
    "Trzebiemir",
    "Trzebiemysł",
    "Trzebiesław",
    "Trzebisław",
    "Trzebomysł",
    "Trzebor",
    "Trzebowit",
    "Twardomir",
    "Twardosław",
    "Twardostoj",
    "Tworzymir",
    "Tworzysław",
    "Ubysław",
    "Uchacz",
    "Uniebog",
    "Unieboż",
    "Uniedrog",
    "Uniegost",
    "Uniemir",
    "Uniemysł",
    "Unierad",
    "Uniesław",
    "Uniewit",
    "Unieżyr",
    "Unimir",
    "Unirad",
    "Unisław",
    "Uściwoj",
    "Wacław",
    "Warcisław",
    "Warcsław",
    "Warsław",
    "Wędziemir",
    "Wicław",
    "Wicsław",
    "Wielebor",
    "Wielebyt",
    "Wieledrog",
    "Wielesław",
    "Wielimir",
    "Wielisław",
    "Wielsław",
    "Wiercisław",
    "Wiesław",
    "Więcemiar",
    "Więcemier",
    "Więcemił",
    "Więcemir",
    "Więcerad",
    "Więcesław",
    "Więcław",
    "Więcmier",
    "Więcsław",
    "Więsław",
    "Wilczan",
    "Wilczęta",
    "Wilk",
    "Wilkomir",
    "Wirciżyr",
    "Wirzchosław",
    "Wisław",
    "Witan",
    "Witomir",
    "Witomysł",
    "Witosław",
    "Witosz",
    "Witsław",
    "Władysław",
    "Właścibor",
    "Włocław",
    "Włocsław",
    "Włodzimierz",
    "Włodzimir",
    "Włodzisław",
    "Włościbor",
    "Włościbyt",
    "Włościwoj",
    "Wociech",
    "Wojan",
    "Wojbor",
    "Wojciech",
    "Wojemił",
    "Wojesław",
    "Wojisław",
    "Wojmir",
    "Wojsław",
    "Wolebor",
    "Wolemir",
    "Wolimir",
    "Wolisław",
    "Wolmir",
    "Wolrad",
    "Wosław",
    "Wrocisław",
    "Wrociwoj",
    "Wrocsław",
    "Wrosław",
    "Wszabor",
    "Wszebąd",
    "Wszebor",
    "Wszeborz",
    "Wszeciech",
    "Wszegniew",
    "Wszemiar",
    "Wszemił",
    "Wszemir",
    "Wszemysł",
    "Wszerad",
    "Wszesiodł",
    "Wszesuł",
    "Wszetopełk",
    "Wświebor",
    "Wysław",
    "Wyszabor",
    "Wyszebor",
    "Wyszemir",
    "Wyszesław",
    "Wyszetrop",
    "Wyszomir",
    "Wyszymir",
    "Zadar",
    "Zamir",
    "Zawisza",
    "Zbelut",
    "Zbigniew",
    "Zbrosław",
    "Zbygniew",
    "Zbyhniew",
    "Zbylut",
    "Zbysław",
    "Zbywoj",
    "Zdamir",
    "Zdawuj",
    "Zdzibor",
    "Zdziczest",
    "Zdziebąd",
    "Zdziebor",
    "Zdziebud",
    "Zdziegod",
    "Zdziegrod",
    "Zdziemił",
    "Zdziemir",
    "Zdzierad",
    "Zdziesław",
    "Zdziesuł",
    "Zdziewit",
    "Zdziewuj",
    "Zdzigod",
    "Zdzigrod",
    "Zdzimir",
    "Zdzisław",
    "Zdzistryj",
    "Zdziwoj",
    "Zdziwuj",
    "Ziemomysł",
    "Ziemowit",
    "Znamir",
    "Zwnisław",
    "Żaba",
    "Żałoba",
    "Żegota",
    "Żelibor",
    "Żelibrat",
    "Żelidrag",
    "Żeligniew",
    "Żelimysł",
    "Żelisław",
    "Żelistryj",
    "Żeliwuj",
    "Żerosław",
    "Żuk",
    "Żur",
    "Żyła",
    "Żyłka",
    "Żyrosław",
  ],
};



export const maleRussianNames = {
  type: "picker",
  list: [
    "Abagor",
    "Abamon",
    "Abataly",
    "Abelyar",
    "Abid",
    "Abily",
    "Abnody",
    "Abram",
    "Aburom",
    "Adam",
    "Afanasy",
    "Agafangel",
    "Agafodor",
    "Agafon",
    "Agafonik",
    "Agafopod",
    "Agafopus",
    "Agap",
    "Agapion",
    "Agapit",
    "Agapy",
    "Agat",
    "Agav",
    "Agavva",
    "Albert",
    "Alexander",
    "Alexey",
    "Amvrosy",
    "Anatoly",
    "Andrei",
    "Andrey",
    "Anton",
    "Arkadiy",
    "Arkady",
    "Artemy",
    "Artyom",
    "Artyom",
    "Avda",
    "Avdakt",
    "Avdelay",
    "Avdey",
    "Avdifaks",
    "Avdiky",
    "Avdiyes",
    "Avdon",
    "Avel",
    "Avenir ",
    "Aventin ",
    "Averky",
    "Avgar",
    "Avgury",
    "Avgust",
    "Avgustin",
    "Avian ",
    "Avim ",
    "Avimelekh",
    "Avip",
    "Avit",
    "Aviv",
    "Avksenty",
    "Avksily",
    "Avksivy",
    "Avkt",
    "Avram ",
    "Avrelian",
    "Avrely",
    "Avrey",
    "Avros",
    "Avsey",
    "Avtonom",
    "Avudim",
    "Avundy",
    "Avva",
    "Avvakir",
    "Avvakum ",
    "Bogdan",
    "Boris ",
    "Budimir",
    "Daniel",
    "Daniil",
    "Danila ",
    "David ",
    "Denis ",
    "Dmitry",
    "Eduard ",
    "Elisei",
    "Fedot",
    "Feofan",
    "Fyodor",
    "Gavriil",
    "Gennady",
    "Genrikh",
    "Georgy ",
    "Gerasim",
    "German ",
    "Gleb",
    "Grigory",
    "Grischa",
    "Ignat",
    "Ilarion",
    "Ilya",
    "Iosif",
    "Ivan",
    "Jaroslav",
    "Kirill",
    "Kliment",
    "Kolya",
    "Konstantin",
    "Lavrentiy",
    "Lev",
    "Leonid",
    "Lev ",
    "Pyotr",
    "Lukyan",
    "Matvei",
    "Maxim ",
    "Miron ",
    "Mstislav ",
    "Nectarios",
    "Nikita ",
    "Nikola",
    "Nikolay",
    "Oleg",
    "Osip",
    "Ossip",
    "Panteleimon",
    "Pavel",
    "Pavsikakiy",
    "Prokhor",
    "Prokopy",
    "Ratimir",
    "Rodion",
    "Roman ",
    "Rostislav ",
    "Ruslan ",
    "Sasha ",
    "Simeon",
    "Simon ",
    "Slava ",
    "Stanislav ",
    "Stepan ",
    "Svetoslav",
    "Sviatoslav",
    "Tikhon",
    "Timofey",
    "Timur ",
    "Trifon",
    "Trofim",
    "Vadim",
    "Valentin",
    "Valery",
    "Vasily",
    "Veniamin",
    "Victor ",
    "Vitalii",
    "Vladilen",
    "Vladimir ",
    "Vladislav",
    "Vsevolod",
    "Vyacheslav",
    "Yakov",
    "Yaroslav",
    "Yefim",
    "Yegor",
    "Yermolay",
    "Yevgeny",
    "Yury",
    "Zakhar",
    "Zinovy",
  ],
};


export const WHFMaleHumanNames = {
  type: "picker",
  list: [
    "Abelhard",
    "Abelhelm",
    "Admund",
    "Adred",
    "Adric",
    "Agis",
    "Alaric",
    "Alberic",
    "Albrecht",
    "Aldebrand",
    "Aldred",
    "Aldric",
    "Alfreid",
    "Alric",
    "Altmar",
    "Andre",
    "Andred",
    "Andric",
    "Anselhelm",
    "Anton",
    "Arne",
    "Arnulf",
    "Axel",
    "Axelbrand",
    "Baldred",
    "Baldric",
    "Baldwin",
    "Balthasar",
    "Barnabas",
    "Bart",
    "Bartolf",
    "Bartomar",
    "Bernolt",
    "Bertold",
    "Bertolf",
    "Boris",
    "Bruno",
    "Burgolf",
    "Calvin",
    "Casimir",
    "Caspar",
    "Cedred",
    "Conrad",
    "Corvin",
    "Dagmar",
    "Dankmar",
    "Dankred",
    "Dekmar",
    "Detlef",
    "Diebold",
    "Diel",
    "Dieter",
    "Dietfried",
    "Dietmar",
    "Dietmund",
    "Dietrich",
    "Dirk",
    "Donat",
    "Durnhelm",
    "Eber",
    "Eckel",
    "Eckhart",
    "Edgar",
    "Edmund",
    "Edwin",
    "Ehrhart",
    "Ehrl",
    "Ehrwig",
    "Eldred",
    "Elmeric",
    "Emil",
    "Engel",
    "Engelbert",
    "Engelbrecht",
    "Engelhart",
    "Eodred",
    "Eomund",
    "Erasmus",
    "Erdman",
    "Erdred",
    "Erich",
    "Erkenbrand",
    "Erman",
    "Ernst",
    "Erwin",
    "Eugen",
    "Eustasius",
    "Ewald",
    "Fabian",
    "Faustus",
    "Felix",
    "Ferdinand",
    "Fleugweiner",
    "Fosten",
    "Franz",
    "Frediger",
    "Fredric",
    "Friebald",
    "Friedrich",
    "Fulko",
    "Gawin",
    "Gerber",
    "Gerhart",
    "Gerlach",
    "Gernar",
    "Gerolf",
    "Gilbrecht",
    "Gisbert",
    "Giselbrecht",
    "Gismar",
    "Goran",
    "Gosbert",
    "Goswin",
    "Gotfried",
    "Gothard",
    "Gottolf",
    "Gotwin",
    "Gregor",
    "Greimold",
    "Grimwold",
    "Griswold",
    "Guido",
    "Gundolf",
    "Gundred",
    "Gunnar",
    "Gunter",
    "Gunther",
    "Gustaf",
    "Hadred",
    "Hadwin",
    "Hagar",
    "Hagen",
    "Haldred",
    "Halman",
    "Hamlyn",
    "Hans",
    "Harbrand",
    "Harman",
    "Hartmann",
    "Haug",
    "Heidric",
    "Heimar",
    "Heinfried",
    "Heinman",
    "Heinrich",
    "Heinz",
    "Helmut",
    "Henlyn",
    "Hermann",
    "Herwin",
    "Hieronymus",
    "Hildebart",
    "Hildebrand",
    "Hildemar",
    "Hildemund",
    "Hildred",
    "Hildric",
    "Horst",
    "Hugo",
    "Igor",
    "Ingwald",
    "Jander",
    "Jekil",
    "Jodokus",
    "Johann",
    "Jonas",
    "Jorg",
    "Jorn",
    "Josef",
    "Jost",
    "Jurgen",
    "Karl",
    "Kaspar",
    "Klaus",
    "Kleber",
    "Konrad",
    "Konradin",
    "Kurt",
    "Lamprecht",
    "Lanfried",
    "Lanric",
    "Lanwin",
    "Leo",
    "Leopold",
    "Levin",
    "Liebert",
    "Liebrecht",
    "Liebwin",
    "Lienhart",
    "Linus",
    "Lodwig",
    "Lothar",
    "Lucius",
    "Ludwig",
    "Luitpold",
    "Lukas",
    "Lupold",
    "Lupus",
    "Luther",
    "Lutolf",
    "Madred",
    "Magnus",
    "Mandred",
    "Manfred",
    "Mathias",
    "Max",
    "Maximillian",
    "Meiner",
    "Meinhart",
    "Meinolf",
    "Mekel",
    "Merkel",
    "Nat",
    "Nathandar",
    "Nicodemus",
    "Odamar",
    "Odric",
    "Odwin",
    "Olbrecht",
    "Oldred",
    "Oldric",
    "Ortlieb",
    "Ortolf",
    "Osric",
    "Oswald",
    "Oswin",
    "Otfried",
    "Otto",
    "Otwin",
    "Owin",
    "Paulus",
    "Prospero",
    "Ragen",
    "Ralf",
    "Rambrecht",
    "Ranald",
    "Randulf",
    "Ranulf",
    "Reikhard",
    "Rein",
    "Reiner",
    "Reinhard",
    "Reinolt",
    "Reuban",
    "Rigo",
    "Roderic",
    "Rolf",
    "Ruben",
    "Rudel",
    "Rudgar",
    "Rudolf",
    "Rufus",
    "Ruprecht",
    "Sebastian",
    "Semund",
    "Sepp",
    "Sieger",
    "Siegfried",
    "Siegmund",
    "Sigismund",
    "Sigric",
    "Steffan",
    "Tankred",
    "Theoderic",
    "Tilmann",
    "Tomas",
    "Trubald",
    "Trubert",
    "Udo",
    "Ulfman",
    "Ulfred",
    "Ulli",
    "Ulman",
    "Uto",
    "Valdred",
    "Valdric",
    "Varl",
    "Viggo",
    "Viktor",
    "Vilmar",
    "Volker",
    "Volkhard",
    "Volkin",
    "Volkrad",
    "Voltz",
    "Walbrecht",
    "Waldor",
    "Waldred",
    "Walther",
    "Warmund",
    "Werner",
    "Wilbert",
    "Wilfried",
    "Wilhelm",
    "Woldred",
    "Wolfgang",
    "Wolfhart",
    "Wolfram",
    "Wulf",
    "Xavier",

    //non whfrp
    "Gebhard",
    "Widekind",
    "Bertram"
  ],
};

let polishFirst = [
  "Bachorza",
  "Barcław",
  "Barcsław",
  "Barnim",
  "Barnisław",
  "Bądzsław",
  "Bąsław",
  "Bdzigost",
  "Bedgost",
  "Bezprym",
  "Będomir",
  "Będzieciech",
  "Będziemir",
  "Będziemirz",
  "Będzimir",
  "Będzimysł",
  "Biecław",
  "Biecsław",
  "Blizan",
  "Blizbor",
  "Blizborz",
  "Bochwał",
  "Bodan",
  "Bogchwał",
  "Bogdaj",
  "Bogdał",
  "Bogdan",
  "Bogdasz",
  "Bogfał",
  "Bogmieł",
  "Bogmił",
  "Bogodał",
  "Bogodan",
  "Bogodar",
  "Bogofał",
  "Bogomieł",
  "Bogomił",
  "Bogosław",
  "Bogowid",
  "Bogsław",
  "Boguchał",
  "Boguchwał",
  "Bogudan",
  "Bogudar",
  "Bogufał",
  "Bogumieł",
  "Bogumił",
  "Bogumysław",
  "Bogurad",
  "Bogured",
  "Bogusąd",
  "Bogusław",
  "Bogwidza",
  "Bogwiedz",
  "Bohusław",
  "Bojan",
  "Bolan",
  "Bolebor",
  "Boleczaj",
  "Boleczest",
  "Bolegor",
  "Bolelut",
  "Bolemir",
  "Bolemysł",
  "Bolesław",
  "Bolesta",
  "Bolęta",
  "Bolibąd",
  "Bolibor",
  "Bolko",
  "Boromir",
  "Borut",
  "Boruta",
  "Borzej",
  "Borzęta",
  "Borzgniew",
  "Borzuj",
  "Borzygniew",
  "Borzym",
  "Borzymir",
  "Borzysław",
  "Borzywoj",
  "Borzywuj",
  "Bosław",
  "Bożciech",
  "Bożdar",
  "Bożebor",
  "Bożeciech",
  "Bożydar",
  "Bożysław",
  "Bracsław",
  "Branibor",
  "Bratmił",
  "Bratomił",
  "Bratomir",
  "Bratosław",
  "Bratosz",
  "Bratumił",
  "Braturad",
  "Bratysław",
  "Bretmił",
  "Bretomił",
  "Brocsław",
  "Brodzisław",
  "Bromir",
  "Bronimir",
  "Bronisąd",
  "Bronisław",
  "Broniwoj",
  "Bronsław",
  "Brosław",
  "Brunisław",
  "Brzestryk",
  "Brzezdob",
  "Brzezdoma",
  "Brzezpraw",
  "Brzezstryk",
  "Budziboj",
  "Budzigniew",
  "Budzimir",
  "Budzisław",
  "Budziwoj",
  "Budziwuj",
  "Budzsław",
  "Budźwoj",
  "Byczek",
  "Bygost",
  "Bytomir",
  "Chalimir",
  "Chalisław",
  "Chocian",
  "Chociebąd",
  "Chociebor",
  "Chociemir",
  "Chociesław",
  "Chocimier",
  "Chocimir",
  "Chocimirz",
  "Chocsław",
  "Chwalęta",
  "Chwalibog",
  "Chwalimir",
  "Chwalisław",
  "Ciechomir",
  "Ciechosław",
  "Cierpisław",
  "Ciesław",
  "Cieszbor",
  "Cieszęta",
  "Cieszmiar",
  "Cieszmier",
  "Cieszmir",
  "Cieszybor",
  "Cieszygor",
  "Cieszym",
  "Cieszymiar",
  "Cieszymier",
  "Cieszymir",
  "Cieszymysł",
  "Cieszyrad",
  "Cieszysław",
  "Cisław",
  "Czabor",
  "Czajęta",
  "Czasław",
  "Czcibor",
  "Czcirad",
  "Czcisław",
  "Czedrog",
  "Czesbor",
  "Czesław",
  "Czębor",
  "Czędomir",
  "Częsbor",
  "Częstobor",
  "Częstogoj",
  "Częstomir",
  "Częstowoj",
  "Czścibor",
  "Dadzbog",
  "Dalbor",
  "Dalebor",
  "Daleborz",
  "Dalegor",
  "Dalemiar",
  "Dalemir",
  "Dalestryj",
  "Dalewin",
  "Dalibor",
  "Dalimiar",
  "Dalimir",
  "Dalwin",
  "Dargomier",
  "Dargorad",
  "Dargosław",
  "Derwan",
  "Długomił",
  "Dobiegniew",
  "Dobielut",
  "Dobiemiar",
  "Dobiemier",
  "Dobiemiest",
  "Dobiemir",
  "Dobiesław",
  "Dobimir",
  "Dobosław",
  "Dobrobąd",
  "Dobrociech",
  "Dobrogniew",
  "Dobrogost",
  "Dobrogoszcz",
  "Dobromier",
  "Dobromił",
  "Dobromir",
  "Dobromysł",
  "Dobromysław",
  "Dobrosiodł",
  "Dobrosław",
  "Dobrosuł",
  "Dobrowit",
  "Dobrowoj",
  "Dobrutro",
  "Dobrzegniew",
  "Domabor",
  "Domaborz",
  "Domagniew",
  "Domamir",
  "Domarad",
  "Domaradz",
  "Domared",
  "Domasław",
  "Domastoj",
  "Domastryj",
  "Domasuł",
  "Domauj",
  "Domawuj",
  "Domażyr",
  "Domiemir",
  "Domorad",
  "Domosław",
  "Drahobysz",
  "Drahomir",
  "Drogmir",
  "Drogodziej",
  "Drogomił",
  "Drogomir",
  "Drogomysł",
  "Drogoradz",
  "Drogosław",
  "Drogowit",
  "Drohobysz",
  "Drohomir",
  "Dromił",
  "Dziebor",
  "Dziersław",
  "Dzierżykraj",
  "Dzierżysław",
  "Dziesław",
  "Dzisław",
  "Dziwigor",
  "Dziwisław",
  "Falibog",
  "Falibor",
  "Falimir",
  "Falimirz",
  "Falisław",
  "Gardomir",
  "Głowka",
  "Gniemir",
  "Gnierat",
  "Gniewko",
  "Gniewomiar",
  "Gniewomier",
  "Gniewomir",
  "Gniewosz",
  "Gocław",
  "Godosław",
  "Godzimir",
  "Godzisław",
  "Godzsław",
  "Gorazd",
  "Gorsław",
  "Gorzysław",
  "Gosław",
  "Gostmił",
  "Gostomysł",
  "Gościmiar",
  "Gościmir",
  "Gościrad",
  "Gościsław",
  "Gościwid",
  "Gościwit",
  "Gościwuj",
  "Goworek",
  "Grochot",
  "Grodzisław",
  "Grodzsław",
  "Gromisław",
  "Grot",
  "Grzmisław",
  "Grzymisław",
  "Grzymosław",
  "Grzymsław",
  "Grzysław",
  "Himisław",
  "Hodysław",
  "Hubysław",
  "Huniemir",
  "Huniesław",
  "Imisław",
  "Izasław",
  "Izbelut",
  "Izbor",
  "Izbygniew",
  "Izbylut",
  "Jaczemir",
  "Jaczewoj",
  "Jaksa",
  "Janisław",
  "Jarogniew",
  "Jaromiar",
  "Jaromir",
  "Jaropełk",
  "Jarosław",
  "Jarostryj",
  "Jawor",
  "Jerogniew",
  "Jeromiar",
  "Jeromier",
  "Jerosław",
  "Jezior",
  "Jimisław",
  "Jirosław",
  "Juniesław",
  "Jutrogost",
  "Jutrowoj",
  "Jutrowuj",
  "Kajmir",
  "Kalmir",
  "Kanimier",
  "Kanimir",
  "Kanmił",
  "Kazimiar",
  "Kazimier",
  "Kazimierz",
  "Kazimir",
  "Kazimirz",
  "Kaźmir",
  "Koprzywa",
  "Korostawic",
  "Korostawiec",
  "Krzecsław",
  "Krzesąd",
  "Krzesimir",
  "Krzesisław",
  "Krzesław",
  "Krzysław",
  "Kwalimir",
  "Kwalisław",
  "Kwiatek",
  "Laliczaj",
  "Lasota",
  "Lech",
  "Lechosław",
  "Lederg",
  "Lelistryj",
  "Lesław",
  "Leszek",
  "Litobor",
  "Lubgost",
  "Lubodrog",
  "Lubomir",
  "Lubomirz",
  "Lubomysł",
  "Luboradz",
  "Lubowid",
  "Lucsław",
  "Ludmar",
  "Ludmił",
  "Ludomer",
  "Ludomił",
  "Ludomir",
  "Ludosław",
  "Ludziwoj",
  "Lutmiar",
  "Lutobor",
  "Lutogniew",
  "Lutomiar",
  "Lutomir",
  "Lutomysł",
  "Lutosław",
  "Lutsław",
  "Małogost",
  "Małomir",
  "Małostryj",
  "Małostryk",
  "Małowid",
  "Małowuj",
  "Manomir",
  "Markusław",
  "Masław",
  "Mezamir",
  "Męcimir",
  "Męcisław",
  "Męcsław",
  "Męsław",
  "Miecisław",
  "Miecsław",
  "Mieczysław",
  "Miełosław",
  "Miesław",
  "Miestwin",
  "Mieszek",
  "Mieszko",
  "Milan",
  "Milej",
  "Milęta",
  "Miłgost",
  "Miłobąd",
  "Miłobor",
  "Miłobrat",
  "Miłochat",
  "Miłoczat",
  "Miłodrog",
  "Miłodziad",
  "Miłogost",
  "Miłorad",
  "Miłosław",
  "Miłostryj",
  "Miłosz",
  "Miłowan",
  "Miłowit",
  "Miłowuj",
  "Miłwit",
  "Minigniew",
  "Minogniew",
  "Mirogniew",
  "Mirogod",
  "Mironieg",
  "Mirosław",
  "Misław",
  "Modlibog",
  "Modliboż",
  "Mogiłek",
  "Mojmir",
  "Mojsław",
  "Morzysław",
  "Mrocław",
  "Mrocsław",
  "Mroczesław",
  "Mroczsław",
  "Mroczysław",
  "Mrosław",
  "Mszczuj",
  "Mszczujwoj",
  "Mścibor",
  "Mścigniew",
  "Mścisław",
  "Mściwoj",
  "Mściwuj",
  "Mysław",
  "Myślibor",
  "Myślidar",
  "Myślim",
  "Myślimir",
  "Nacław",
  "Naczęmiar",
  "Naczęmier",
  "Naczęmir",
  "Naczęrad",
  "Naczęsław",
  "Naczęwoj",
  "Naczęwuj",
  "Nadar",
  "Nadbor",
  "Nadmir",
  "Nadziej",
  "Nagod",
  "Namir",
  "Namysław",
  "Nasiębąd",
  "Nasiębor",
  "Nasław",
  "Nawoj",
  "Niebor",
  "Niebylec",
  "Niecisław",
  "Niedał",
  "Niedamir",
  "Niedan",
  "Niedaniec",
  "Niezamysł",
  "Ninowłod",
  "Nowosiodł",
  "Objęsław",
  "Ocięsław",
  "Odolan",
  "Okrzesław",
  "Opoka",
  "Osiębor",
  "Osięgniew",
  "Ostrobod",
  "Ostrogniew",
  "Ostrowod",
  "Pakosław",
  "Pomścibor",
  "Poznan",
  "Poznomir",
  "Prosimir",
  "Przebąd",
  "Przebor",
  "Przecław",
  "Przecsław",
  "Przedabog",
  "Przedbor",
  "Przedmir",
  "Przedpełk",
  "Przedpołk",
  "Przedsław",
  "Przedwoj",
  "Przedwor",
  "Przedwuj",
  "Przemęt",
  "Przemieł",
  "Przemił",
  "Przemir",
  "Przemysł",
  "Przemysław",
  "Przesław",
  "Przybor",
  "Przybygniew",
  "Przybylut",
  "Przybymir",
  "Przybyrad",
  "Przybysław",
  "Przybysza",
  "Przybywoj",
  "Przybywuj",
  "Przysnobor",
  "Przywit",
  "Racibor",
  "Raciborz",
  "Racigniew",
  "Racimiar",
  "Racimir",
  "Racisław",
  "Racław",
  "Racsław",
  "Radmir",
  "Radociech",
  "Radogost",
  "Radomiar",
  "Radomił",
  "Radomir",
  "Radosław",
  "Radost",
  "Radosz",
  "Radowan",
  "Radowit",
  "Radowuj",
  "Radsław",
  "Radsuł",
  "Radzan",
  "Radzim",
  "Rasław",
  "Ratsław",
  "Recibor",
  "Recław",
  "Recsław",
  "Redosław",
  "Redsław",
  "Resław",
  "Retsław",
  "Rocław",
  "Rocsław",
  "Rodomieł",
  "Rodomił",
  "Rodsław",
  "Rolirad",
  "Rosław",
  "Rościgniew",
  "Rościsław",
  "Rozniat",
  "Rozniata",
  "Rus",
  "Rzędzimir",
  "Rzędzisław",
  "Rzędziwoj",
  "Sambor",
  "Samogost",
  "Samosąd",
  "Sęczygniew",
  "Sędomir",
  "Sędosław",
  "Sędowin",
  "Sędowoj",
  "Sędzigrod",
  "Sędzimir",
  "Sędzisław",
  "Sędziwoj",
  "Sędziwuj",
  "Sędźwoj",
  "Sężyr",
  "Siabor",
  "Sidło",
  "Siebąd",
  "Siebor",
  "Sieciebor",
  "Sieciech",
  "Sieciesław",
  "Siecław",
  "Siecsław",
  "Siedlewit",
  "Siemar",
  "Siemidrog",
  "Siemierz",
  "Siemił",
  "Siemimił",
  "Siemimysł",
  "Siemir",
  "Siemirad",
  "Siemisław",
  "Siemmił",
  "Siemomysł",
  "Siemomysław",
  "Siemoradz",
  "Siemosław",
  "Siemowit",
  "Siepraw",
  "Sierosław",
  "Siesław",
  "Siestrzemił",
  "Siestrzewit",
  "Sietbor",
  "Sięgniew",
  "Siężyr",
  "Sirosław",
  "Sjęgniew",
  "Skamir",
  "Skarbimir",
  "Skarbimirz",
  "Skarbisław",
  "Skardmir",
  "Sławciech",
  "Sławobor",
  "Sławociech",
  "Sławomiar",
  "Sławomir",
  "Sławosław",
  "Smysław",
  "Snowid",
  "Sobiebor",
  "Sobiemir",
  "Sobiemysł",
  "Sobierad",
  "Sobiesąd",
  "Sobiesław",
  "Sobieżyr",
  "Solisław",
  "Spycigniew",
  "Spycimir",
  "Spycisław",
  "Spyćmier",
  "Spyćmierz",
  "Spyćmir",
  "Stanibor",
  "Stanimir",
  "Stanisław",
  "Stasław",
  "Stogniew",
  "Stoigniew",
  "Stoisław",
  "Stojan Wygnan",
  "Stojgniew",
  "Stojsław",
  "Stomir",
  "Stosław",
  "Strachomir",
  "Strogobor",
  "Strogomir",
  "Stronisław",
  "Strosław",
  "Strzałek",
  "Strzebor",
  "Strzecław",
  "Strzecsław",
  "Strzedziwoj",
  "Strzedzsław",
  "Strzesław",
  "Strzesz",
  "Strzeszko",
  "Strzeżymir",
  "Strzeżysław",
  "Sudywoj",
  "Sulibor",
  "Sulibrat",
  "Sulidziad",
  "Suligost",
  "Sulim",
  "Sulima",
  "Sulimiar",
  "Sulimir",
  "Sulirad",
  "Sulisław",
  "Sulistryj",
  "Suliwuj",
  "Sulmir",
  "Swojsław",
  "Swosław",
  "Szabor",
  "Szczęsny",
  "Szczodr",
  "Szebor",
  "Szenbor",
  "Ścibor",
  "Świebąd",
  "Świebor",
  "Świeborz",
  "Świeciech",
  "Świecław",
  "Świedarg",
  "Świegniew",
  "Świelub",
  "Świemił",
  "Świemir",
  "Świerad",
  "Świesław",
  "Święcesław",
  "Święcsław",
  "Święsław",
  "Świętobor",
  "Świętomir",
  "Świętopełk",
  "Świętosław",
  "Świrad",
  "Taniebor",
  "Tasław",
  "Tatomier",
  "Tatomir",
  "Tatumir",
  "Tęgomir",
  "Toligniew",
  "Tolisław",
  "Tomił",
  "Tomir",
  "Tomisław",
  "Tosław",
  "Trzebiebor",
  "Trzebiegost",
  "Trzebiemiar",
  "Trzebiemier",
  "Trzebiemir",
  "Trzebiemysł",
  "Trzebiesław",
  "Trzebisław",
  "Trzebomysł",
  "Trzebor",
  "Trzebowit",
  "Twardomir",
  "Twardosław",
  "Twardostoj",
  "Tworzymir",
  "Tworzysław",
  "Ubysław",
  "Uchacz",
  "Uniebog",
  "Unieboż",
  "Uniedrog",
  "Uniegost",
  "Uniemir",
  "Uniemysł",
  "Unierad",
  "Uniesław",
  "Unimir",
  "Unisław",
  "Uściwoj",
  "Wacław",
  "Warcisław",
  "Warcsław",
  "Warsław",
  "Wędziemir",
  "Wicsław",
  "Wielebor",
  "Wielebyt",
  "Wieledrog",
  "Wielesław",
  "Wielimir",
  "Wielisław",
  "Wielsław",
  "Wiercisław",
  "Wiesław",
  "Więcemiar",
  "Więcemier",
  "Więcemił",
  "Więcemir",
  "Więcerad",
  "Więcesław",
  "Więcław",
  "Więcmier",
  "Więcsław",
  "Więsław",
  "Wilkomir",
  "Wirciżyr",
  "Wirzchosław",
  "Wisław",
  "Witan",
  "Witomir",
  "Witomysł",
  "Witosław",
  "Witosz",
  "Witsław",
  "Władysław",
  "Właścibor",
  "Włocław",
  "Włocsław",
  "Włodzimierz",
  "Włodzimir",
  "Włodzisław",
  "Włościbor",
  "Włościbyt",
  "Włościwoj",
  "Wociech",
  "Wojan",
  "Wojbor",
  "Wojciech",
  "Wojemił",
  "Wojesław",
  "Wojisław",
  "Wojmir",
  "Wojsław",
  "Wolebor",
  "Wolemir",
  "Wolimir",
  "Wolisław",
  "Wolmir",
  "Wolrad",
  "Wosław",
  "Wrocisław",
  "Wrociwoj",
  "Wrocsław",
  "Wrosław",
  "Wszeciech",
  "Wszegniew",
  "Wszemiar",
  "Wszemił",
  "Wszemir",
  "Wszemysł",
  "Wszerad",
  "Wszetopełk",
  "Wświebor",
  "Wysław",
  "Wyszabor",
  "Wyszebor",
  "Wyszemir",
  "Wyszesław",
  "Wyszetrop",
  "Wyszomir",
  "Wyszymir",
  "Zadar",
  "Zamir",
  "Zawisza",
  "Zbigniew",
  "Zbrosław",
  "Zbygniew",
  "Zbyhniew",
  "Zbysław",
  "Zbywoj",
  "Zdamir",
  "Zdawuj",
  "Zdzibor",
  "Zdziemił",
  "Zdziemir",
  "Zdzierad",
  "Zdziesław",
  "Zdziesuł",
  "Zdziewit",
  "Zdziewuj",
  "Zdzigod",
  "Zdzigrod",
  "Zdzimir",
  "Zdzisław",
  "Zdziwoj",
  "Zdziwuj",
  "Ziemomysł",
  "Ziemowit",
  "Znamir",
  "Żegota",
  "Żelibor",
  "Żelibrat",
  "Żelidrag",
  "Żeligniew",
  "Żelimysł",
  "Żelisław",
  "Żelistryj",
  "Żeliwuj",
  "Albrecht",
  "Andrzej",
  "Michał",
  "Teodoryk",
  "Beniamin",
  "Abel",
  "Jan",
  "Mikołaj",
  "Aleksander",
  "Gotard",
  "Paweł",
  "Wincenty",
  "Hinczka",
  "Idzi",
  "Imram",
  "Iwan",
  "Jakub",
  "Janusz",
  "Jarand",
  "Spytek",
  "Marcin",
  "Piotr",
  "Klemens",
  "Krystyn",
  "Maciej",
  "Maćko",
  "Męcina",
  "Sędziwój",
  "Otton",
  "Rafał",
  "Sągniew",
  "Katarzyna",
  "Sławko",
  "Tomasz",
  "Bartosz",
  "Wierzbięta",
  "Wiseł",
  "Wszebor",
  "Zyndram",
  "Żelisław",
  "Dobko",
  "Henryk",
  "Albrecht",
  "Michał",
  "Andrzej",
  "Teodoryk",
  "Zbigniew",
  "Beniamin",
  "Abel",
  "Mikołaj",
  "Janusz",
  "Niekrasz",
  "Abraham",
  "Ścibor",
  "Stanisław",
  "Wygand",
  "Jan",
  "Dobrogost",
  "Florian",
  "Gniewosz",
  "Aleksander",
  "Paweł",
  "Wincenty",
  "Hinczka",
  "Idzi",
  "Imram",
  "Iwan",
  "Jakub",
  "Jarand",
  "Jarosław",
  "Marcin",
  "Piotr",
  "Kiełcz",
  "Klemens",
  "Dziersław",
  "Przedpełk",
  "Maciej",
  "Maćko",
  "Męcina",
  "Mszczuj",
  "Dobiesław",
  "Zawisza",
  "Sędziwój",
  "Otton",
  "Prokop",
  "Rafał",
  "Sławko",
  "Spycimir",
  "Spytko",
  "Strasz",
  "Tomasz",
  "Bartosz",
  "Wiseł",
  "Wojciech",
  "Wojsław",
  "Wszebor",
  "Zyndram",
  "Żelisław"

]

let polishLast = [
  "z Kłecka",
  "Brodnicki",
  "Awdaniec",
  "z Buczacza",
  "Balicki",
  "Bar",
  "Bąk",
  "z Uzarzewa",
  "Biel",
  "Błociszewski",
  "Bogoria",
  "ze Służewa",
  "z Grabowa",
  "Granowski",
  "z Rogowa",
  "Jucha",
  "z Sowiny",
  "z Klecia",
  "z Obichowa",
  "z Rudomina",
  "Skarbek",
  "z Góry",
  "z Błociszewa",
  "Naszon",
  "z Ostrowiec",
  "z Jani",
  "z Ossolina",
  "z Rożnowa",
  "ze Szczekocin",
  "z Tuliszkowa",
  "z Iwna",
  "Tarnowski",
  "Kamieniecki",
  "Kuropatwa",
  "Kurowski",
  "Lasocki",
  "Ligęza",
  "z Gorzyc",
  "z Łaska",
  "z Krowicy",
  "Gruszecki",
  "z Wąsosza",
  "z Prudnika",
  "Kierzkowski",
  "z Wrocimowic",
  "ze Sławska",
  "Mediolański",
  "Melsztyński",
  "z Melsztyna",
  "z Konina",
  "z Taczewa",
  "z Michałowa",
  "z Oporowa",
  "z Tarnawy",
  "ze Skrzynna",
  "Niedźwiedzki",
  "Butwidowicz",
  "z Gawarca",
  "Odrowąż",
  "ze Sprowy i Zagórza",
  "Oleśnicki",
  "z Oleśnicy",
  "Czerwony",
  "Ossoliński",
  "Ostroróg",
  "z Pilczy",
  "Pakosławic",
  "Pilecki",
  "Szafraniec",
  "Polak",
  "Poniecki",
  "z Goraja",
  "z Kopydłowa",
  "Ptaszkowski",
  "z Gołuchowa",
  "Rzeszowski",
  "z Konarów",
  "Skotnicki",
  "Szydłowiecki",
  "Smolnicki",
  "Leliwita",
  "Stadnicki",
  "z Miąsowej",
  "z Białaczowa",
  "Szarlejski",
  "Szczodrowski",
  "z Ostaszewa",
  "ze Ściborzyc",
  "z Łaźnina",
  "Wezenborg",
  "z Paniewic",
  "Czambor",
  "Włostowski",
  "z Kościelca",
  "z Michowa",
  "Wszebor",
  "Wszeborowic",
  "Stary",
  "Czarny",
  "Garbowa",
  "z Brzezia",
  "Złodziej",
  "z Biskupic",
  "z Maszkowic",
  "Żegota",
  "Złotoręki",
  "z Odolanowa",
  "Dunin",
  "z Prawkowic",
  "Gryfita",
  "Wydżga",
  "z Kłecka",
  "z Buczacza",
  "Balicki",
  "Bar",
  "Bąk",
  "z Uzarzewa",
  "Biel",
  "Błociszewski",
  "Bogoria",
  "Bolesta",
  "Brzozogłowy",
  "Buczacki Jazłowiecki",
  "Buczacki",
  "Jazłowiecki",
  "Butwidowicz",
  "Chamiec",
  "Chełmski",
  "Ciołek z Żelechowa",
  "z Żelechowa",
  "Ciołek",
  "Długosz z Niedzielska",
  "Długosz",
  "z Niedzielska",
  "Nałęcz",
  "Farurej z Garbowa",
  "z Korytnicy",
  "z Dalewic",
  "Gorajski",
  "z Grabowa",
  "Granowski",
  "z Rogowa",
  "Jucha",
  "z Sowiny",
  "z Klecia",
  "z Rudomina",
  "Skarbek z Góry",
  "Naszon z Ostrowiec",
  "z Jani",
  "z Ossolina",
  "z Rożnowa",
  "z Sienna",
  "ze Szczekocin",
  "z Tuliszkowa",
  "z Grabi i Brudzewa",
  "z Iwna",
  "Jarosławski",
  "Kamieniecki",
  "Kmita",
  "Ruszczy",
  "Strzelec",
  "z Kobylan",
  "Kobylański",
  "Konopka",
  "Siestrzeniec",
  "z Kopydłowa",
  "Kuropatwa",
  "Kurowski",
  "Ligęza",
  "Ligęza z Gorzyc",
  "z Łaska",
  "z Krowicy",
  "Gruszecki",
  "Kierzkowski",
  "z Wąsosza",
  "z Prudnika",
  "z Wrocimowic",
  "ze Sławska",
  "Mediolański",
  "z Konina",
  "z Taczewa",
  "z Michałowa",
  "z Oporowa",
  "z Tarnawy",
  "ze Skrzynna",
  "Niedźwiedzki",
  "Odrowąż",
  "Oleśnicki",
  "Oleśnicki Czerwony",
  "Ossoliński",
  "Ostroróg",
  "z Pilczy",
  "Pakosławic",
  "Pilecki Otta",
  "Szafraniec",
  "Polak",
  "Poniecki",
  "z Goraja",
  "z Gołuchowa",
  "Rzeszowski",
  "Bogoria Skotnicki",
  "Skrzyńska",
  "Szydłowiecki"
]

let germanFirst = WHFMaleHumanNames.list
let germanLast = [
  "von Alvensleben",
  "de Grumbach",
  "von Brunswick",
  "Kraus",
  "Dilber",
  "von Esbeke",
  "Decker",
  "von Randecke",
  "von Schluck",
  "Fridericus",
  "von Eberstein",
  "Sanderus",
  "Jordanus",
  "von Esbeke",
  "von Lorenen",
  "von Hohenzollern",
  "von Scharnitzky",
  "von Plauen",
  "von Feuchtwangen",
  "von Montfort",
  "von Jungingen",
  "von Wallenrode",
  "von Tieffen",
  "von Beldenz",
  "von Blumenthal",
  "von Liechtenstein",
  "von Heideck",
  "von Tettau",
  "von Löben",
  "von Richtenberg",
  "von Horne",
  "von der Groeben",
  "von Nüsler",
  "von Lengerke",
  "von Rammin",
  "von Reuss",
  "von der Goltz",
  "von Zinnenberg",
  "von Rüdiger",
  "von Plötzke",
  "von Tannheim",
  "von Arnsberg",
  "von Schweinichen",
  "von Sacken",
  "von Lüder",
  "von Hochberg",
  "von Haunoldstein",
  "von Falkenhausen",
  "von Rechenberg",
  "von Mühlheim",
  "von der Schulenburg",
  "von Tümpling",
  "von Loeben",
  "von und zu Hanstein",
  "von Slatnitz",
  "von Puchheim",
  "von Thurn",
  "von Wallenrode",
  "von Hirschfeld",
  "von Erlangen",
  "von Breitenlandenberg",
  "von Raesfeld",
  "von Nürnberg",
  "von Zinzendorf",
  "von Seebach",
  "von Tübingen",
  "von Scharffenberg",
  "von Guttenberg",
  "von Loeben",
  "von Schoenfeld",
  "von Dönhoff",
  "von Wartenberg",
  "von Wallenrode",
  "von Laubenberg",
  "von Bocholtz",
  "von Rohr",
  "von Wrangel",
  "von Tänzing",
  "von Eberstein",
  "von Plauen",
  "von Eppingen",
  "von Wallenrode",
  "von Neumarkt",
  "von Sulzbürg",
  "von Schelklingen",
  "von Salza",
  "von Pfirt",
  "von Lüder",
  "von Kospoth",
  "von Heideck",
  "von Jungingen",
  "von Bistram",
  "von Nassau",
  "von Schleinitz",
  "von Manteuffel",
  "von Heringen",
  "von Schellenberg",
  "von Zedlitz",
  "von Hessen",
  "von Trotha",
  "von der Osten",
  "von Danckelmann",
  "von der Brüggen",
  "von Moltke",
  "von Lehwaldt",
  "von Blanckensee",
  "von Schenkendorf",
  "von Thümen",
  "von Plotho",
  "von Bismarck",
  "von Königsdorf",
  "von Tiefen",
  "von Walbrun",
  "von Heiden",
  "von Kaphengst",
  "von Berlichingen",
  "von Mellenthin",
  "von Kunheim",
  "von Hünfeld",
  "von Liegnitz",
  "von Leiffen",
  "von Brederode",
  "von der Gröben",
  "von Dewitz",
  "von Brandenburg",
  "von Galen",
  "von Dücker",
  "von Zitzewitz",
  "von Montfort",
  "von Eltz",
  "von Hartmann",
  "von der Goltz",
  "von Bellin",
  "von Bernstorff",
  "von Schlichting",
  "von Tarnov",
  "von Schönaich",
  "von Ramm",
  "von Eicke",
  "von Teuffel",
  "von Horn",
  "von Wredow",
  "von Schilling",
  "von Lauenburg",
  "von Brüning",
  "von Röbel",
  "von Alvensleben",
  "von Kanne",
  "von Homburg",
  "von Schellendorf",
  "von Rettberg",
  "von Halle",
  "von Runge",
  "von Giese",
  "von der Borch",
  "von Trott",
  "von Homburg",
  "von Pfuel",
  "von Schöning",
  "von Königsmarck",
  "von Boineburg",
  "von Posadowsky",
  "von Wertheim",
  "von Pleissenburg",
  "von Thüna",
  "von Hünerbein",
  "von Hatzfeld",
  "von Rüchel",
  "von Bülow",
  "von Lüchow",
  "von Dithmarschen",
  "von Traun",
  "von Plettenberg",
  "von Egloffstein",
  "von Wöhrmann",
  "von Gilsa",
  "von Hattorf",
  "von Nettelhorst",
  "von Griesheim",
  "von Boetticher",
  "von Groeben",
  "von Sanden",
  "von Stosch",
  "von Goeben",
  "von Schladen",
  "von Seherr-Thoss",
  "von Giese",
  "von Hacke",
  "von Kalckreuth",
  "von Wangelin",
  "von Boeselager",
  "von Zieten",
  "von Jeinsen",
  "von Hatten",
  "von Trotha",
  "von Rödern",
  "von Rauch",
  "von Schwerin",
  "von Tiesenhausen",
  "von Brandenstein",
  "von Bartensleben",
  "von Arnim",
  "von Lietzenburg",
  "von Quadt",
  "von Plotho",
  "von Wedel",
  "von Syburg",
  "von Gröben",
  "von Witzleben",
  "von Reitzenstein",
  "von Kottwitz",
  "von Donop",
  "von Wallenrode",
  "von Knobelsdorff",
  "von Trotha",
  "von Seelen",
  "von Plötz",
  "von Sparr",
  "von Wardenburg",
  "von Hertefeld",
  "von Schenk",
  "von Schlichting",
  "von Polenz",
  "von Buchwald",
  "von Egloffstein",
  "von Sparneck",
  "von Thurheim"
]
let frankishFirst = [
  "Hugh",
  "Robert",
  "Everard",
  "Bernard",
  "André",
  "Bertrand",
  "Philippe",
  "Odo",
  "Arnaud",
  "Gérard",
  "Robert",
  "Gilbert",
  "Phillipe",
  "Guillaume",
  "Pedro",
  "Armand",
  "Richard",
  "Guillaume",
  "Renaud",
  "Thomas",
  "Guillaume",
  "Thibaud",
  "Jacques",
  "Godfrey",
  "Baldwin",
  "Fulk",
  "Amalric",
  "Henry",
  "Raymond",
  "Arnold",
  "Pere",
  "Guy",
  "Lorencio",
  "Gilbert",
  "Pedro",
  "William",
  "Evelio",
  "Adémar",
  "Riperto",
  "Stephen",
  "Peter",
  "Berenguer",
  "Simon",
  "William",
  "Hugues",
  "Hoston",
  "Adam",
  "Richard",
  "Geoffroy",
  "Robert",
  "Thomas",
  "Alain",
  "Guillaume",
  "Lawrence",
  "Roger",
  "Aimery",
  "Guillaume",
  "Alain",
  "Roncelin",
  "Humbert",
  "Gui",
  "Henri",
  "Marcus",
  "Geoffrey",
  "Jean",
  "Payen",
  "Everard",
  "Guillaume",
  "Geoffroy",
  "David",
  "Eustache",
  "Robert",
  "Raoul",
  "Arn",
  "André",
  "Olivier",
  "Pons",
  "Renaud",
  "Fabien",
  "Foulques",
  "Amaury",
  "Jean",
  "Guillaume",
  "Hugues",
  "Matthew",
  "Gérard",
  "Jerar",
  "Arnaud",
  "Gérard",
  "Hugues",
  "Déodat",
  "Foulques",
  "Pierre",
  "Hugolin",
  "Raimond",
  "Déodat",
  "Jeremy",
  "David",
  "Bertrand",
  "Roustan",
  "Raymond",
  "Ripert",
  "Nicholis",
  "Pons",
  "Raimbaud",
  "Guillaume",
  "Robert",
  "Hugues",
  "Pons",
  "Raimbaud",
  "Guillaume",
  "Robert",
  "Geoffrey",
  "Gauthier",
  "Albert",
  "Baudouin",
  "Aimé",
  "Eluard",
  "Gilbert",
  "Pons",
  "Constant",
  "Humbert",
  "Francon",
  "Gui",
  "Stefan",
  "Guillaume",
  "Pons",
  "Armand",
  "Jacques",
  "Lawrence",
  "Damase",
  "Etienne",
  "Pierre",
  "Albert",
  "Geoffroy",
  "Laurent",
  "Ode",
  "Boniface",
  "Hermand",
  "Martino",
  "Guglielmo",
  "Bonifazio",
  "Gerardo",
  "Alberico",
  "Gaimardo",
  "Aimerico",
  "Giovanni",
  "Goffredo",
  "Giacomo",
  "Dalmazio",
  "Pietro",
  "Ermanno",
  "Enrico",
  "Bianco",
  "Uguccione",
  "Oberto",
  "Guilluame",
  "Artusio",
  "Frédéric",
  "Bertram",
  "Gérard",
  "Barozzi",
  "Falco",
  "Humbert",
  "Aimery",
  "Témeric",
  "Gui",
  "Foulques",
  "Francon",
  "Amblard",
  "Raymond",
  "Hermand",
  "Oberto",
  "Guilluame",
  "Artusio",
  "André",
  "Béranger",
  "Seiher",
  "Godechaux",
  "Walter",
  "Hurson",
  "Aimon",
  "Reric",
  "Bryony",
  "Oberto",
  "Guilluame",
  "Artusio",
  "Odon",
  "Gilbert",
  "Jean",
  "Gerbert",
  "William",
  "Irmengaud",
  "Barthélemy",
  "Gilles",
  "Étienne",
  "Amaury",
  "Thibaud",
  "Robert",
  "Baudouin",

  "Aimon",
  "Geoffroy",
  "Geoffroy",
  "Robert",
  "Geoffroy",
  "Jacques",
  "Baudouin",

  "Barthélemy",
  "Aimon",

  "Stefan",
  "Guillaume",
  "Pons",
  "Armand",
  "Jacques",
  "Lawrence",
  "Damase",
  "Etienne",
  "Pierre",
  "Albert",
  "Geoffroy",
  "Laurent",
  "Ode",
  "Boniface",
  "Hermand",
  "Martino",
  "Guglielmo",
  "Bonifazio",
  "Gerardo",
  "Alberico",
  "Gaimardo",
  "Aimerico",
  "Giovanni",
  "Goffredo",
  "Giacomo",
  "Dalmazio",
  "Pietro",
  "Ermanno",
  "Enrico",
  "Bianco",
  "Uguccione",
  "Oberto",
  "Guilluame",
  "Artusio",
  "Frédéric",
  "Bertram",
  "Gérard",
  "Barozzi",
  "Falco",
  "Humbert",
  "Aimery",
  "Témeric",
  "Gui",
  "Foulques",
  "Francon",
  "Amblard",
  "Raymond",
  "Hermand",
  "Oberto",
  "Guilluame",
  "Artusio",
  "André",
  "Béranger",
  "Seiher",
  "Godechaux",
  "Walter",
  "Hurson",
  "Aimon",
  "Reric",
  "Bryony",
  "Oberto",
  "Guilluame",
  "Artusio",
  "Odon",
  "Gilbert",
  "Jean",
  "Gerbert",
  "William",
  "Irmengaud",
  "Barthélemy",
  "Gilles",
  "Étienne",
  "Amaury",
  "Thibaud",
  "Robert",
  "Baudouin",
  "Aimon",
  "Geoffroy",
  "Geoffroy",
  "Robert",
  "Geoffroy",
  "Jacques",
  "Baudouin",
  "Barthélemy",
  "Aimon",

  //portugese
  "Guilherme",
  "Hugo",
  "Pedro",
  "Gualdim",
  "Lopo",
  "Fernando",
  "Gomes",
  "Martim",
  "Estêvão",
  "Guilherme",
  "Paio",
  "Gonçalo",
  "Beltrão",
  "João",
  "Afonso",
  "Lourenço",
  "Vasco",
  "Berenger",
  "Guillem",
  "Hugues",
  "Pere",
  "Bérenger",
  "Rodrigue",


  ///

  'Achard', 'Adalbero', 'Adalbert', 'Adalram', 'Adam', 'Aimery', 'Ainard',
  'Airald', 'Alan', 'Alard', 'Albert', 'Aldo', 'Alelm', 'Alexander',
  'Alfonso', 'Alo', 'Alram', 'Alvisus', 'Amadeus', 'Amanieu', 'Andrew',
  'Anfred', 'Angerius', 'Ansaldo', 'Ansellus',
  'Anselm', 'Anseric', 'Antelme', 'Archibald', 'Arduin', 'Arni', 'Arnold',
  'Arnulf', 'Artald', 'Arved', 'Aslak', 'Astanove', 'Attropius', 'Aubrey',
  'Aufan', 'Autran', 'Aznar', 'Baldric', 'Baldwin', 'Barisan', 'Bartholomew',
  'Bego', 'Bellacosa', 'Bellay', 'Bencelin', 'Benedict', 'Berald', 'Berengar',
  'Beringer', 'Berlai', 'Bernard', 'Berthold', 'Bertrand', 'Bohemond',
  'Bonfilius', 'Boso', 'Bracas', 'Brunet', 'Bruno', 'Burchard', 'Caffaro',
  'Centule', 'Chalo', 'Charles', 'Chastard', 'Cherfron', 'Clarembald', 'Conan',
  'Cono', 'Conrad', 'Constantine', 'Constantius', 'Corba', 'Daibert', 'Daniel',
  'Dithmar', 'Dodo', 'Domenico', 'Doon', 'Drogo', 'Durand', 'During', 'Eberhard',
  'Ebles', 'Edgar', 'Egilolf', 'Ekkehard',
  'Emerias', 'Emicho', 'Emma', 'Engelbert', 'Englelm', 'Engelmar', 'Engelrand',
  'Erald', 'Erard', 'Erkenbald', 'Ermengald', 'Ernest', 'Eurvin', 'Eustace',
  'Everard', 'Fantin', 'Farald', 'Faucon', 'Florina', 'Folkmar', 'Fortun',
  'Franco', 'Frederick', 'Frumold', 'Fulbert', 'Fulcher', 'Fulk', 'Gandier',
  'Garcia', 'Garin', 'Garnier', 'Garsadon', 'Gastinellus', 'Gaston', 'Gaucher',
  'Gebhard', 'Geldemar', 'Geoffrey', 'Gerald', 'Gerard', 'Gerardo', 'Gerault',
  'Gerbrand', 'Gerhard', 'Gernand', 'Gerold', 'Gerulf', 'Gervais', 'Gervase',
  'Gerwald', 'Ghino', 'Giacomo', 'Gibert', 'Gilbert', 'Gilduin', 'Gilo',
  'Girismann', 'Giselbert', 'Giselher', 'Giso', 'Godfrey', 'Godric', 'Goldinellus',
  'Gontier', 'Gosbert', 'Gospert', 'Goswin', 'Gotmann', 'Gottschalk', 'Gouffier',
  'Gozelo', 'Grimbald', 'Grimoald', 'Guarin', 'Guiraut', 'Gunscelin', 'Gunter',
  'Guy', 'Hadmar', 'Halldor', 'Hamelin', 'Hamo', 'Hamundr', 'Hartmann',
  'Hauvines', 'Helias', 'Helie', 'Heliodore', 'Henry', 'Heraclius', 'Herbert',
  'Heribrand', 'Herluin', 'Herman', 'Hermann', 'Herment', 'Herpert', 'Hervey',
  'Hezelo', 'Hildebert', 'Hilduin', 'Hildulf', 'Hosto', 'Hubert'

]

let frankishLast = [
  "de Payens",
  "de Craon",
  "des Barres",
  "de Tremelay",
  "de Montbard",
  "de Blanchefort",
  "de Milly",
  "de St Amand",
  "de Toroge",
  "de Ridefort",
  "de Sablé",
  "Horal",
  "de Plessis",
  "de Chartres",
  "de Montaigu",
  "de Périgord",
  "de Bures",
  "de Sonnac",
  "de Vichiers",
  "Bérard",
  "de Beaujeu",
  "Gaudin",
  "de Molay",
  "of Rigaud",
  "Gaucebert",
  "of Bedocio",
  "de Rovira",
  "of Barcelona",
  "Geoffrey",
  "of Torroja",
  "of Avinyó",
  "of Sellón",
  "Plaza",
  "of Canet",
  "Eral",
  "(of) Rigaud",
  "of Caercino",
  "of Claramunt",
  "de Monteagudo",
  "Cadell",
  "of Montrodón",
  "Ramirez",
  "de Claret",
  "Marescalci",
  "of Azylach",
  "of Puig Guigone",
  "of Montpesat",
  "Patot",
  "of Montlaur",
  "of Belmonte",
  "of Serra",
  "of Cardona",
  "of Jouy",
  "of Montañana",
  "of Pontóns",
  "of Castellnou",
  "of Moncada",
  "of San Justo",
  "of Lenda",
  "Heath",
  "d'Argentein",
  "de Saint-Omer",
  "de Somervila",
  "de Hastings",
  "Fitzstephen",
  "de Neuham",
  "Bérard",
  "Alain",
  "Cadeil",
  "Ryckman",
  "St. Leger",
  "de Sainte-Maure",
  "de la Gravelle",
  "Martel",
  "de Montfort",
  "de Sandford",
  "de Argentein",
  "Amblard",
  "de Fos",
  "de Pairaud",
  "de Foresta",
  "de Torteville",
  "de Faverham",
  "de Sandford",
  "de Tourville",
  "de More",
  "Stronge",
  "of St. Albans",
  "de Paduinan",
  "Mallebeench",
  "of Ogerstan",
  "MacLean-de Corzon",
  "de Harcourt",
  "de Sheffield",
  "de Keyes",
  "Howard",
  "Brand",
  "de Ferrers",
  "de Lacy",
  "Marshal",
  "de Rolleston",
  "de Goldingham",
  "LeBlanc",
  "de Charney",
  "De St. Leger",
  "de Craon",
  "des Barres",
  "Pavet",
  "Foucher",
  "de Rancourt",
  "le Chien",
  "de Miliaco",
  "de Montliard",
  "Erail",
  "LeBlanc",
  "de Coulours",
  "Oeil-de-Boeuf",
  "de l'Aigle",
  "Royier",
  "de la Roche",
  "d'Albon",
  "de Lille",
  "d'Albon",
  "Damase",
  "de Vichier",
  "de Basenville",
  "Deon LeBlanc",
  "de Saint-Michel",
  "de Pairaud",
  "de la Roche",
  "le François",
  "de Mallay",
  "de Pairaud",
  "John Norris",
  "de Villiers",
  "de Poitous",
  "de Bedos",
  "de Montpierre",
  "de Bourbouton",
  "de Panaz",
  "de l'Etang",
  "de Biais",
  "de Bras",
  "Itier",
  "le Chien",
  "Hugolin",
  "Laugier",
  "Seguis",
  "de Chambarrand",
  "Dupuy",
  "Laseter",
  "d'Alex",
  "Alziari",
  "Hugolin",
  "de Silva",
  "de Pierrevert",
  "de Campion",

  "Martello",
  "de la Fossa",
  "Rigaud",
  "de Perigors",
  "de Turisellis",
  "de Ryckman",
  "de Fenolar",
  "de Sissey",
  "de Beaujeu",
  "de Greffier",
  "de Cannelis",
  "de Pierrevert",
  "d'Outremont",
  "de Beaune",
  "de Vaudrie",
  "Champiny",
  "de Rochefort",
  "d'Orleans",
  "de Périgord",
  "di San Michele",
  "Gabillone",
  "da Canelli",
  "de Finoleriis",

  //portugese

  "Ricardo",
  "Martins",
  "Froilaz",
  "de Montoire",
  "Arnaldo",
  "Pais",
  "Fernandes",
  "Dias",
  "Ramires",
  "Álvares de Alvito",
  "Anes",
  "Sanches",
  "Belmonte",
  "Martins",
  "Gomes",
  "Nunes",
  "Valverde",
  "Escritor",
  "de Coll",
  "de Cardona",
  "de Jouy",
  "de Belmonte",
  "de Montcada",
  "Ibañez"








]
export const crusaderNames = function () {
  let list = []
  list.push(randomizeFromArray(germanFirst) + " " + randomizeFromArray(germanLast))
  list.push(randomizeFromArray(germanFirst) + " " + randomizeFromArray(germanLast))

  list.push(randomizeFromArray(frankishFirst) + " " + randomizeFromArray(frankishLast))
  list.push(randomizeFromArray(frankishFirst) + " " + randomizeFromArray(frankishLast))
  list.push(randomizeFromArray(frankishFirst) + " " + randomizeFromArray(frankishLast))

  list.push(randomizeFromArray(polishFirst) + " " + randomizeFromArray(polishLast))
  return {
    type: "pickerRoller",
    list
  }
}

export const commonerNames = function () {
  let list = []
  list.push(randomizeFromArray(germanFirst))
  list.push(randomizeFromArray(germanFirst))

  list.push(randomizeFromArray(frankishFirst))
  list.push(randomizeFromArray(frankishFirst))
  list.push(randomizeFromArray(frankishFirst))

  list.push(randomizeFromArray(polishFirst))
  list.push(randomizeFromArray(maleSlavicNames.list))
  list.push(randomizeFromArray(maleRussianNames.list))
  return {
    type: "pickerRoller",
    list
  }
}
